spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.profiles.active=h2

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.metrics.tags.application=personal-finance-service

application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG
spring.jpa.defer-datasource-initialization=true
